// bench/apps/vue/src/NeutroField.vue
<script setup lang="ts">
import type { FormInstance } from '@neutro/form-core'
import { useVueFormPath } from '@neutro/form-vue'

const props = defineProps<{
  form: FormInstance<any>
  name: string
  renders: Record<string, number>
}>()

const { value } = useVueFormPath(props.form, props.name)
props.renders[props.name] = (props.renders[props.name] ?? 0) + 1
</script>

<template>
  <input
    :data-testid="`neutro-${name}`"
    :value="value as string"
    @input="form.set(name as any, ($event.target as HTMLInputElement).value)"
  />
</template>

// bench/apps/svelte/src/NeutroField.svelte
<script lang="ts">
  import type { FormInstance } from '@neutro/form-core'
  import { useSvelteFormPath } from '@neutro/form-svelte'

  const {
    form,
    name,
    renders,
  }: {
    form: FormInstance<Record<string, string>>
    name: string
    renders: Record<string, number>
  } = $props()

  const field = useSvelteFormPath(form, name)

  $effect.pre(() => {
    void $field.value
    renders[name] = (renders[name] ?? 0) + 1
  })
</script>

<input
  data-testid={`neutro-${name}`}
  value={$field.value as string}
  oninput={(e) => form.set(name as any, (e.target as HTMLInputElement).value)}
/>
