// bench/apps/svelte/src/App.svelte
<script lang="ts">
  import { createForm } from '@neutro/form-core'
  import { createForm as createTsForm } from '@tanstack/svelte-form'
  import { createForm as createFelteForm } from 'felte'
  import NeutroField from './NeutroField.svelte'
  import TanStackField from './TanStackField.svelte'
  import FelteField from './FelteField.svelte'
  import NeutroAsyncPage from './NeutroAsyncPage.svelte'
  import TanStackAsyncPage from './TanStackAsyncPage.svelte'
  import FelteAsyncPage from './FelteAsyncPage.svelte'
  import NeutroCancelPage from './NeutroCancelPage.svelte'
  import TanStackCancelPage from './TanStackCancelPage.svelte'
  import FelteCancelPage from './FelteCancelPage.svelte'

  const path = window.location.pathname

  const FIELD_COUNT = Number(new URLSearchParams(window.location.search).get('fields')) || 10
  const FIELDS = Array.from({ length: FIELD_COUNT }, (_, i) => `field${i}`)

  // --- Render counters ---
  const neutroRenders: Record<string, number> = {}
  const tanstackRenders: Record<string, number> = {}
  const felteRenders: Record<string, number> = {}
  ;(window as any).__neutroRenders = neutroRenders
  ;(window as any).__tanstackRenders = tanstackRenders
  ;(window as any).__felteRenders = felteRenders
  ;(window as any).__resetRenders = () => {
    for (const k in neutroRenders) neutroRenders[k] = 0
    for (const k in tanstackRenders) tanstackRenders[k] = 0
    for (const k in felteRenders) felteRenders[k] = 0
  }

  const neutroForm = createForm({
    initialValues: Object.fromEntries(FIELDS.map((n) => [n, ''])),
  })

  const tsForm = createTsForm(() => ({
    defaultValues: Object.fromEntries(FIELDS.map((n) => [n, ''])),
  }))

  const { form: felteAction, data: felteData, setFields } = createFelteForm({
    initialValues: Object.fromEntries(FIELDS.map((n) => [n, ''])),
  })
</script>

{#if path === '/async/neutro'}
  <NeutroAsyncPage />
{:else if path === '/async/tanstack'}
  <TanStackAsyncPage />
{:else if path === '/async/felte'}
  <FelteAsyncPage />
{:else if path === '/cancel/neutro'}
  <NeutroCancelPage />
{:else if path === '/cancel/tanstack'}
  <TanStackCancelPage />
{:else if path === '/cancel/felte'}
  <FelteCancelPage />
{:else}
  <!-- Re-renders page -->
  <section data-testid="neutro-form">
    {#each FIELDS as name}
      <NeutroField form={neutroForm} {name} renders={neutroRenders} />
    {/each}
  </section>

  <section data-testid="tanstack-form">
    {#each FIELDS as name}
      <tsForm.Field {name}>
        {#snippet children(field)}
          <TanStackField {field} {name} renders={tanstackRenders} />
        {/snippet}
      </tsForm.Field>
    {/each}
  </section>

  <form use:felteAction>
    <section data-testid="felte-form">
      {#each FIELDS as name}
        <FelteField {name} data={felteData} renders={felteRenders} {setFields} />
      {/each}
    </section>
  </form>
{/if}

// bench/apps/vue/src/App.vue
<script setup lang="ts">
import { createForm } from '@neutro/form-core'
import { useForm as useVeeForm } from 'vee-validate'
import NeutroField from './NeutroField.vue'
import VeeField from './VeeField.vue'
import NeutroAsyncPage from './NeutroAsyncPage.vue'
import VeeAsyncPage from './VeeAsyncPage.vue'
import NeutroCancelPage from './NeutroCancelPage.vue'
import VeeCancelPage from './VeeCancelPage.vue'

const path = window.location.pathname

// ---- Re-renders page setup ----
const FIELD_COUNT = Number(new URLSearchParams(window.location.search).get('fields')) || 10
const FIELD_NAMES = Array.from({ length: FIELD_COUNT }, (_, i) => `field${i}`)

const neutroForm = createForm({
  initialValues: Object.fromEntries(FIELD_NAMES.map(n => [n, ''])),
})
const neutroRenders: Record<string, number> = {}
;(window as any).__neutroRenders = neutroRenders

const veeRenders: Record<string, number> = {}
;(window as any).__veeRenders = veeRenders

;(window as any).__resetRenders = () => {
  for (const k in neutroRenders) neutroRenders[k] = 0
  for (const k in veeRenders) veeRenders[k] = 0
}

// Vee-Validate requires useForm() to establish the provide/inject form context.
// Must be called unconditionally — composables cannot be conditional in <script setup>.
// On async pages the context goes unused but causes no harm.
useVeeForm()
</script>

<template>
  <!-- Async pages -->
  <NeutroAsyncPage v-if="path === '/async/neutro'" />
  <VeeAsyncPage v-else-if="path === '/async/vee'" />
  <NeutroCancelPage v-else-if="path === '/cancel/neutro'" />
  <VeeCancelPage v-else-if="path === '/cancel/vee'" />

  <!-- Re-renders page -->
  <div v-else>
    <section data-testid="neutro-form">
      <NeutroField
        v-for="name in FIELD_NAMES"
        :key="name"
        :form="neutroForm"
        :name="name"
        :renders="neutroRenders"
      />
    </section>
    <section data-testid="vee-form">
      <VeeField
        v-for="name in FIELD_NAMES"
        :key="name"
        :name="name"
        :renders="veeRenders"
      />
    </section>
  </div>
</template>
