// packages/adapters/react/src/index.ts
import type { FormInstance, FormState, GetPathValue, Path } from '@neutro/form-core';
import React, { useCallback, useRef, useSyncExternalStore } from 'react';

export function useForm<T extends object>(
  form: FormInstance<T>
): FormState<T> & Omit<FormInstance<T>, 'subscribe' | 'getState' | '_subscribeToActions'> {
  const state = useSyncExternalStore(form.subscribe, form.getState, form.getState);
  return {
    ...state,
    get: form.get,
    set: form.set,
    connect: form.connect,
    submit: form.submit,
    handleSubmit: form.handleSubmit,
    reset: form.reset,
    batch: form.batch,
    subscribeToPath: form.subscribeToPath,
    validate: form.validate,
    getPayload: form.getPayload,
    getAriaProps: form.getAriaProps,
    getFieldMode: form.getFieldMode,
    getConnectedCount: form.getConnectedCount,
    destroy: form.destroy,
    arrayAppend: form.arrayAppend,
    arrayInsert: form.arrayInsert,
    arrayRemove: form.arrayRemove,
    arrayMove: form.arrayMove,
    arraySwap: form.arraySwap,
    setErrors: form.setErrors,
    clearErrors: form.clearErrors,
    resetField: form.resetField,
    isDirty: form.isDirty,
    isFieldDirty: form.isFieldDirty,
    isFieldValid: form.isFieldValid,
  } as FormState<T> & Omit<FormInstance<T>, 'subscribe' | 'getState' | '_subscribeToActions'>;
}

export function useFormPath<T extends object, P extends Path<T>>(
  form: FormInstance<T>,
  path: P
): GetPathValue<T, P> {
  const subscribe = useCallback(
    (onStoreChange: () => void) => form.subscribeToPath(path, () => onStoreChange()),
    [form, path]
  );
  const getSnapshot = useCallback(() => form.get(path), [form, path]);
  return useSyncExternalStore(subscribe, getSnapshot, getSnapshot) as GetPathValue<T, P>;
}

export function useWatch<T extends object>(
  form: FormInstance<T>,
  paths: Path<T> | string | Array<Path<T> | string>
): Record<string, unknown> {
  const pathArray = Array.isArray(paths) ? paths : [paths]
  const [watched, setWatched] = React.useState<Record<string, unknown>>(() => {
    const snap: Record<string, unknown> = {}
    pathArray.forEach(p => { snap[p as string] = form.get(p as any) })
    return snap
  })

  React.useEffect(() => {
    const stop = form.watch(paths, (vals) => setWatched({ ...vals }))
    return stop
  }, [form, JSON.stringify(pathArray)])

  return watched
}

// Zero-rerender hook: wires a DOM input directly via form.connect() without
// touching React state. Equivalent to RHF's register() pattern.
// Cleanups are tracked in a ref so StrictMode double-mount doesn't leak listeners.
export function useFormConnect(form: any) {
  const cleanups = useRef(new Map<string, () => void>());
  return useCallback(
    (path: string, options?: any) => (el: HTMLElement | null) => {
      if (el) {
        cleanups.current.get(path)?.();
        cleanups.current.set(path, form.connect(path, el, options));
      } else {
        cleanups.current.get(path)?.();
        cleanups.current.delete(path);
      }
    },
    [form]
  );
}

// packages/adapters/angular/src/index.ts
import { DestroyRef, inject, NgZone, type Signal, signal } from '@angular/core';
import type { FormInstance, FormState, Path } from '@neutro/form-core';

export interface AngularFormReturn<T extends object> {
  state: Signal<FormState<T>>;
  get: FormInstance<T>['get'];
  set: FormInstance<T>['set'];
  connect: FormInstance<T>['connect'];
  submit: FormInstance<T>['submit'];
  handleSubmit: FormInstance<T>['handleSubmit'];
  reset: FormInstance<T>['reset'];
  batch: FormInstance<T>['batch'];
  validate: FormInstance<T>['validate'];
  subscribeToPath: FormInstance<T>['subscribeToPath'];
  getPayload: FormInstance<T>['getPayload'];
  getAriaProps: FormInstance<T>['getAriaProps'];
  getFieldMode: FormInstance<T>['getFieldMode'];
  getConnectedCount: FormInstance<T>['getConnectedCount'];
  destroy: FormInstance<T>['destroy'];
  arrayAppend: FormInstance<T>['arrayAppend'];
  arrayInsert: FormInstance<T>['arrayInsert'];
  arrayRemove: FormInstance<T>['arrayRemove'];
  arrayMove: FormInstance<T>['arrayMove'];
  arraySwap: FormInstance<T>['arraySwap'];
  setErrors: FormInstance<T>['setErrors'];
  clearErrors: FormInstance<T>['clearErrors'];
  resetField: FormInstance<T>['resetField'];
  isDirty: FormInstance<T>['isDirty'];
  isFieldDirty: FormInstance<T>['isFieldDirty'];
  isFieldValid: FormInstance<T>['isFieldValid'];
}

// Must be called inside an injection context (component constructor or inject() call site).
export function useAngularForm<T extends object>(form: FormInstance<T>): AngularFormReturn<T> {
  const formSignal = signal(form.getState());
  // NgZone.run() ensures signal updates trigger change detection in zone.js apps.
  // In zoneless apps the optional inject returns null and we call set() directly.
  const zone = inject(NgZone, { optional: true });
  const unsubscribe = form.subscribe((s) =>
    zone ? zone.run(() => formSignal.set(s)) : formSignal.set(s)
  );
  inject(DestroyRef).onDestroy(unsubscribe);
  return {
    state: formSignal.asReadonly(),
    get: form.get,
    set: form.set,
    connect: form.connect,
    submit: form.submit,
    handleSubmit: form.handleSubmit,
    reset: form.reset,
    batch: form.batch,
    validate: form.validate,
    subscribeToPath: form.subscribeToPath,
    getPayload: form.getPayload,
    getAriaProps: form.getAriaProps,
    getFieldMode: form.getFieldMode,
    getConnectedCount: form.getConnectedCount,
    destroy: form.destroy,
    arrayAppend: form.arrayAppend,
    arrayInsert: form.arrayInsert,
    arrayRemove: form.arrayRemove,
    arrayMove: form.arrayMove,
    arraySwap: form.arraySwap,
    setErrors: form.setErrors,
    clearErrors: form.clearErrors,
    resetField: form.resetField,
    isDirty: form.isDirty,
    isFieldDirty: form.isFieldDirty,
    isFieldValid: form.isFieldValid,
  };
}

// Returns two readonly Signals for direct template binding.
// Must be called inside an injection context.
export function useAngularFormPath<T extends object>(form: FormInstance<T>, path: string) {
  const value = signal<unknown>(form.get(path));
  const fieldState = signal<{ error?: string; touched?: boolean; dirty?: boolean } | null>(null);
  const zone = inject(NgZone, { optional: true });
  const unsubscribe = form.subscribeToPath(path, (v, fs) => {
    if (zone) {
      zone.run(() => {
        value.set(v);
        fieldState.set(fs);
      });
    } else {
      value.set(v);
      fieldState.set(fs);
    }
  });
  inject(DestroyRef).onDestroy(unsubscribe);
  return { value: value.asReadonly(), fieldState: fieldState.asReadonly() };
}

export function useAngularWatch<T extends object>(
  form: FormInstance<T>,
  paths: Array<Path<T> | string> | Path<T> | string
): Signal<Record<string, unknown>> {
  const destroyRef = inject(DestroyRef)
  const zone = inject(NgZone, { optional: true })
  const pathArray = (Array.isArray(paths) ? paths : [paths]) as string[]

  const initial: Record<string, unknown> = {}
  pathArray.forEach(p => { initial[p] = form.get(p as any) })

  const watched = signal<Record<string, unknown>>(initial)
  const stop = form.watch(pathArray, (vals) => {
    zone ? zone.run(() => watched.set({ ...vals })) : watched.set({ ...vals })
  })
  destroyRef.onDestroy(stop)

  return watched.asReadonly()
}
